before:
  hooks:
  - go mod download
builds:
- id: wxworkbot
  main: ./
  binary: wxworkbot
  env:
  - CGO_ENABLED=0
  ldflags:
  - -w
  - -X github.com/bryant-rh/wxworkbot/cmd/wxworkbot.version={{.Version}}
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
  ignore:
  - goos: windows
    goarch: arm64

archives:
- builds:
  - wxworkbot
  name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
  wrap_in_directory: false
  format: tar.gz
  files:
  - LICENSE